### ISSUE TITLE
Feature request: (Flutter Auth with custom screens)

### ISSUE THREAD

**Issue by law-san-667** [kinde-oss/kinde-flutter-sdk#20]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

I have my custom signin screens for my flutter app and what I am looking for is a method to redirect users to the Kinde verification page. I looked in the doc and it's explained but only for Javascript projects. Maybe I missed the flutter part...

### What solution would you like to see?

Something that could help me is a guide to implement custom signing screens with Flutter sdk, for example on a Next project we got something like this: 
```
router.push(
    `/api/auth/register?org_code=${KINDE_CLIENT_ORG}
    &connection_id=${FACEBOOK_ID}
    &post_login_redirect_url=${`${DEV_ENV
                        ? "http://localhost:3000"
                        : "https://smxew-web.vercel.app"
                    }/auth/callback/client`}`
```

**Comment by malik19995** [comment]
https://docs.kinde.com/authenticate/custom-configurations/custom-authentication-pages/

I believe you're referencing this Javascript implementation. We recently added the integration for using AuthURLParams. 

Please test with the latest version, passing the ConnectionId to the SDK methods via AuthURLParams.

**Comment by malik19995** [comment]
https://docs.kinde.com/design/pages/design-your-welcome-pages/ 

Create your custom design pages using this guide. 

Then, you can simply use the connection ID as explained in the documentation using the AuthUrlParams like in the screenshot below. 
<img width="527" alt="Screenshot 2024-08-05 at 5 47 56 PM" src="https://github.com/user-attachments/assets/30edde1e-7ecb-4407-ae83-ff6d9b62221b">

**Comment by law-san-667** [comment]
Hello, thanks for the answer !

This is indeed what I was looking for but I can't find the section in the doc talking about the flutter implementation and it does not seem theses params are available in the version I'm using (1.0.2 that seems to be the latest) as you can see in the screenshots below
![Capture d’écran 2024-08-05 à 14 00 43](https://github.com/user-attachments/assets/778cfc0d-f1c7-4933-b1e4-bfc61fe5ea82)
![Capture d’écran 2024-08-05 à 14 01 02](https://github.com/user-attachments/assets/c334476c-40ef-43bb-858e-8e2e66529efb)

That's the reason I can't implement what's on the screen you sent:

![Capture d’écran 2024-08-05 à 14 04 27](https://github.com/user-attachments/assets/72befbb1-31dd-44c3-a726-b6e8e6869632)

Maybe I made a mistake somewhere in my implementation but this feature seems not available for flutter_kinde_sdk: 1.0.2

**Comment by malik19995** [comment]
Ah yes, you are correct. 

We've recently added this functionality, which will be live soon on pub.dev

**Comment by onderay** [comment]
Sorry for the delay @law-san-667, v1.0.3 of the SDK should resolve this for you. Are you able to confirm? https://github.com/kinde-oss/kinde-flutter-sdk/releases/tag/1.0.3

**Comment by law-san-667** [comment]
Hey @onderay I just tested and it works perfectly fine and as expected. 
Many thanks for the quick support !
